### ISSUE TITLE
ReplyError: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by lgwebdream** [silverbucket/node-redis-connection-pool#14]
hi,when i use pm2 start app.js，The following error occurred

2|app      | YD For pcweb server listening on port 4000
2|app      | plugins load completed
2|app      | ReplyError: Ready check failed: NOAUTH Authentication required.
2|app      |     at parseError (/opt/node-publish/www/node_modules/redis-parser/lib/parser.js:167:12)
2|app      |     at parseType (/opt/node-publish/www/node_modules/redis-parser/lib/parser.js:228:14)

but node app.js  everything is ok。Beg God help😭

**Comment by silverbucket** [comment]
@lgwebdream does your redis server require authentication to be used?

**Comment by SarasArya** [comment]
Yes it does. I want to authenticate my node.js app as well.

**Comment by nitish24p** [comment]
```javascript
let redisClient = redis.createClient(config.redis.port, config.redis.host);
redisClient.auth(config.redis.password);
```

**Comment by svarughese91** [comment]
I am having this same problem as well!

**Comment by nitish24p** [comment]
@svarughese91 use the ```redisClient.auth``` method as mentioned above. If you are using a host url (amazon cache) then you can find your password in the url itself.
for example ```redis://h:p77sjdbejk84sad7341daba8c26971c157827968f81a62@ec2-54-206-56-30.compute-1.amazonaws.com:56059```
 Then
```
host: ec2-54-206-56-30.compute-1.amazonaws.com
port: 56059
password: p77sjdbejk84sad7341daba8c26971c157827968f81a62
```

**Comment by svarughese91** [comment]
@nitish24p I am trying to try the url but where do I find out the username?  I see you put h and I tried that but that didnt work

**Comment by nitish24p** [comment]
@svarughese91 The redis client doesnt need the username. Can you put a snippet of you init code here.

**Comment by svarughese91** [comment]
@nitish24p ok looks like I was able to authenticate correctly but I am getting this error: 
events.js:141
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/home/ubuntu/TekIT/ITapp/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/ubuntu/TekIT/ITapp/node_modules/redis-parser/lib/parser.js:303:14)



Not sure why here is my code snippet:
```
var client = redis.createClient();
client.auth(redisConfig.redis);


// Create and use a Socket.IO Redis store
var RedisStore = require('socket.io-redis')
io.set('store', new RedisStore({
    redisPub: redis.createClient(redisHost),
    redisSub: redis.createClient(redisHost),
    redisClient: client
}));
```
 

Do you know why I am seeing this error?

**Comment by nitish24p** [comment]
In the createClient method you havent passed host and port?

**Comment by svarughese91** [comment]
@nitish24p ok I tried it with this url but its not working:
client.auth('redis://:' + redisConfig.redis + '@127.0.0.1:6379')

**Comment by nitish24p** [comment]
Im saying this ```var client = redis.createClient(host, port);```

**Comment by svarughese91** [comment]
@nitish24p so like this?
```
var client = redis.createClient('127.0.0.1', '6379');
client.auth(redisConfig.redis);


// Create and use a Socket.IO Redis store
var RedisStore = require('socket.io-redis')
io.set('store', new RedisStore({
    redisPub: redis.createClient(redisHost),
    redisSub: redis.createClient(redisHost),
    redisClient: client
}));
```

**Comment by nitish24p** [comment]
Since i dont know about the socket.io-redis package but your init should be like this
```
var redisClient = redis.createClient('127.0.0.1', '6379');
redisClient.auth("<YOUR_PASSWORD>");
```

**Comment by svarughese91** [comment]
@nitish24p ok I tried that but i get this error:

/home/ubuntu/TekIT/ITapp/node_modules/redis/lib/createClient.js:62
            options.path = port_arg;
                         ^

TypeError: Cannot assign to read only property 'path' of 6379
    at createClient (/home/ubuntu/TekIT/ITapp/node_modules/redis/lib/createClient.js:62:26)
    at Object.exports.createClient (/home/ubuntu/TekIT/ITapp/node_modules/redis/index.js:1084:41)
    at Object.<anonymous> (/home/ubuntu/TekIT/ITapp/Server.js:3417:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by mariothedev** [comment]
None of this works :(
