### ISSUE TITLE
Not get the host i set

### ISSUE THREAD

**Issue by JulianXin** [silverbucket/node-redis-connection-pool#16]
Hi,
    I set the address as '192.168.2.221',but i still got the error 'Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379'

**Comment by silverbucket** [comment]
Hello, nice avatar @JulianXin :D 
Could you please show me the initialization code you're using so I know how you set the IP?

**Comment by JulianXin** [comment]
@silverbucket 

const pool = require('redis-connection-pool')
let redisPool = pool('myRedisPool', {
    host: '192.168.2.221', // 
    port: 6379,
    max_clients: 30,
    perform_checks: false,
    database: 0
});

// redis 链接错误
redisPool.on('error', function (error) {
    console.log(error)
});

**Comment by silverbucket** [comment]
@JulianXin it's weird, I'm not able to reproduce the error, but I just added another test to check for this situation (verify custom host is being set). Could you checkout the github repo and run the `npm test` to see if all tests pass for you? If not, could you paste the failing test info?

**Comment by JulianXin** [comment]
![4 cs lvbra2u57g8 6 yj](https://cloud.githubusercontent.com/assets/17587026/22275152/9c12857a-e2e5-11e6-9a56-d9e854f76b20.png)

Oh,I forgot to tell that I run this on windows7
