### ISSUE TITLE
Incompatibility with fakeredis mock

### ISSUE THREAD

**Issue by Scharnvirk** [silverbucket/node-redis-connection-pool#17]
Hello,

I have encountered a very minor trouble when using fakeredis for testing in my application. 
In redisCheck function, the ready handler looks like this:

```
function () {
      self.version_string = client.server_info.redis_version;
      self.version_array = client.server_info.versions;
      if (self.version_array[0] < 2) {
        self.blocking_support = false;
      }
      client.quit();
      q.resolve(self.version_string);
    }
```

Now, the fakeredis mock does not supply it with server_info, which means self.version_array will be undefined, which in turn will cause JS to blow up on getting zeroth element from an undefined variable.

Proposed solution would be super simple:

```
function () {
      client.server_info = client.server_info || {};
      self.version_string = client.server_info.redis_version;
      self.version_array = client.server_info.versions;
      if (!self.version_array || self.version_array[0] < 2) {
        self.blocking_support = false;
      }
      client.quit();
      q.resolve(self.version_string);
    }
```

However - I am not sure whether this is an issue of fakeredis or redis-connection-pool; but I have a slight preference towards foolproof code hence why am I writing here first. Naturally, fakeredis should also mimic redis properly, but who knows what is wrong with other redis mocks? 

What do you think?

**Comment by silverbucket** [comment]
@Scharnvirk thanks for the report - I agree, defensive code will be better off regardless. The change looks good to me, do you want to submit a pull request?

**Comment by Scharnvirk** [comment]
Sure, one moment please.
