### ISSUE TITLE
ERROR : uncaughtException: pool.getPoolSize is not a function

### ISSUE THREAD

**Issue by JulienStitelet** [silverbucket/node-redis-connection-pool#25]
Hi, 

I'm currently facing a production error: with message : 
uncaughtException: pool.getPoolSize is not a function

in node_modules/redis-connection-pool/src/redis-connection-pool.js:127:40
```
debug('REDIS POOL: [size: ' + pool.getPoolSize() +
                ' avail:' + pool.availableObjectsCount() +
                ' waiting:' + pool.waitingClientsCount() + ']');
```

**Comment by silverbucket** [comment]
@JulienStitelet are you using the latest release?

**Comment by JulienStitelet** [comment]
I'm using the 1.7.1

**Comment by silverbucket** [comment]
@JulienStitelet ah, ok, this is likely a breaking API change with the generic-pool library that we use. Just to double check, you weren't receiving this problem before this release right?

**Comment by JulienStitelet** [comment]
Yup, 1.6.1 was ok

**Comment by JulienStitelet** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/22171760/46147636-5434cf80-c266-11e8-8cb3-80303bd83feb.png">

pool.size can get the information now

**Comment by silverbucket** [comment]
@JulienStitelet great, i'm adding unit tests right now for these method calls so nothing like this slips by in the future.

**Comment by silverbucket** [comment]
@JulienStitelet thanks for the report, i just published `1.7.2`  to npm.

**Comment by JulienStitelet** [comment]
availableObjectsCount => pool.available
But seems waitingClientsCount() has disappeared or has been completely removed ..

**Comment by silverbucket** [comment]
@JulienStitelet yeah I replaced all of them with properties, are you getting any errors ?
