### ISSUE TITLE
Connects with 127.0.0.1 instead of host parameter value when running in a container.

### ISSUE THREAD

**Issue by chainhead** [silverbucket/node-redis-connection-pool#30]
I am running my container as follows:

`docker run --rm -p 80:3001 -it $(pwd)/conf/server.json:/app/conf/server.json -v $(pwd)/conf/redis.json:/app/conf/redis.json username/reponame:tag`

Before making the connection, the `options` object for Redis connection does have the values as defined in `$(pwd)/conf/redis.json`. The connection fails with the following error.

`Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379`

How to get around this problem?

**Comment by silverbucket** [comment]
Could you reduce this down to something outside of docker? Too many factors to consider.

**Comment by silverbucket** [comment]
At first glance it looks like your docker instance is unable to connect to redis.

**Comment by silverbucket** [comment]
https://github.com/silverbucket/node-redis-connection-pool/issues/29
