### ISSUE TITLE
different databases

### ISSUE THREAD

**Issue by ORESoftware** [silverbucket/node-redis-connection-pool#5]
One thing I am confused about with this library - what if you are using different Redis databases (perhaps all of the 16 defaults?)

If I retrieve a connection from the pool, can I tell it what database to do the gets/sets with? Can I retrieve a connection that is connected to one particular database?

I really don't get it.

**Comment by silverbucket** [comment]
Hi @ORESoftware, currently this module doesn't support switching database numbers, however it would be pretty trivial to implement. If you can submit a patch that'd be awesome, otherwise I'll try to get to that sometime soon but it's currently not a huge priority.

**Comment by ORESoftware** [comment]
thanks, at my work we are using 3 of 16 available default DB's. We are starting to need a way to pool connections so we don't just create them willy nilly.

**Comment by silverbucket** [comment]
I was playing around with this and added initial functionality to switch databases. I'm using `client.select` but so far have been unable to verify which database I'm connected to after using this. Are you currently using the same `select` method? When I check `server_info` the data seems to imply `db0` is all that's connected.

**Comment by ORESoftware** [comment]
well currently I am using the ioredis library - this lib allows me to connect to other DBs. Whereas, originally I was using node-redis, which did not make it clear how to connect to different DBs. Neither of the aforemention libs do pooling, as you probably know, so I am looking for external solution to that problem, instead of having to roll my own pool

**Comment by silverbucket** [comment]
Yeah, that's where I am with the `node-redis` library. I've filed an issue about it here: https://github.com/NodeRedis/node_redis/issues/833

We'll see how it goes, if I'm still having trouble I may look into replacing it with `ioredis`.

**Comment by ORESoftware** [comment]
ok cool we are on the same page, let me know if you make strides with pooling with different DBs in this lib, I will be back

**Comment by silverbucket** [comment]
hi @ORESoftware I just pushed a new version of the code which allows you to specify the desired database number during initialization (see updated README). give it a shot and let me know if you have any feedback or problems

**Comment by ORESoftware** [comment]
cool thanks I will check it out
