### ISSUE TITLE
No ttl check support

### ISSUE THREAD

**Issue by djsharma** [silverbucket/node-redis-connection-pool#9]
please include TTL check. I did not found in documentation and in code.

**Comment by silverbucket** [comment]
Do you mean the timeout when connecting to Redis? Or the max time any member of the pool can be idle before an auto-disconnect?

**Comment by djsharma** [comment]
to check whether key expired or ttl remaining.  TTL command that is supported by redis.

**Comment by ayazpasha2434** [comment]
+1
Also, need multi, exec & incr command support.

**Comment by silverbucket** [comment]
Thanks to @ayazpasha2434 for submitting a pull request for this issue: https://github.com/silverbucket/node-redis-connection-pool/pull/11
